# Generated by Django 3.1.1 on 2020-10-07 07:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=50)),
                ('lName', models.CharField(max_length=50)),
                ('mName', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='employee.person')),
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('regdate', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Customer',
            },
            bases=('employee.person',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employee.person')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('maritalStatus', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('spouseName', models.CharField(max_length=50)),
                ('spouseOcc', models.CharField(max_length=20)),
                ('numberOfChildren', models.IntegerField()),
                ('motherName', models.CharField(max_length=50)),
                ('motherOcc', models.CharField(max_length=20)),
                ('fatherName', models.CharField(max_length=50)),
                ('fatherOcc', models.CharField(max_length=20)),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('religion', models.CharField(max_length=50)),
                ('elemSchoolName', models.CharField(blank=True, max_length=50, null=True)),
                ('elemGrade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('elemDateCompleted', models.DateField(blank=True, default=None, null=True)),
                ('elemAwards', models.TextField(blank=True, max_length=100, null=True)),
                ('jhsSchoolName', models.CharField(blank=True, max_length=50, null=True)),
                ('jhsGrade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('jhsDateCompleted', models.DateField(blank=True, default=None, null=True)),
                ('jhsAwards', models.TextField(blank=True, max_length=100, null=True)),
                ('shsSchoolName', models.CharField(blank=True, max_length=50, null=True)),
                ('shsGrade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('shsDateCompleted', models.DateField(blank=True, default=None, null=True)),
                ('shsAwards', models.TextField(blank=True, max_length=100, null=True)),
                ('shsStrand', models.CharField(blank=True, max_length=5, null=True)),
                ('collegeSchoolName', models.CharField(blank=True, max_length=50, null=True)),
                ('collegeCourse', models.CharField(blank=True, max_length=50, null=True)),
                ('collegeLvl', models.IntegerField(blank=True, null=True)),
                ('collegeDateCompleted', models.DateField(blank=True, default=None, null=True)),
                ('collegeAwards', models.TextField(blank=True, max_length=100, null=True)),
                ('postgradSchoolName', models.CharField(blank=True, max_length=50, null=True)),
                ('postgradCourse', models.CharField(blank=True, max_length=50, null=True)),
                ('postgradLvl', models.IntegerField(blank=True, null=True)),
                ('postgradDateCompleted', models.DateField(blank=True, default=None, null=True)),
                ('postgradAwards', models.TextField(blank=True, max_length=100, null=True)),
                ('trainTitle', models.CharField(blank=True, max_length=50, null=True)),
                ('trainSponsors', models.CharField(blank=True, max_length=50, null=True)),
                ('trainDate', models.DateField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'Employee',
            },
            bases=('employee.person',),
        ),
    ]
