# Generated by Django 3.1.1 on 2020-09-18 10:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employee.person')),
                ('regdate', models.DateField(default=datetime.datetime(2020, 9, 18, 18, 49, 28, 791559))),
            ],
            options={
                'db_table': 'Customer',
            },
            bases=('employee.person',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employee.person')),
                ('maritalStatus', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('spouseName', models.CharField(max_length=50)),
                ('spouseOcc', models.CharField(max_length=20)),
                ('numberOfChildren', models.IntegerField()),
                ('motherName', models.CharField(max_length=50)),
                ('motherOcc', models.CharField(max_length=20)),
                ('fatherName', models.CharField(max_length=50)),
                ('fatherOcc', models.CharField(max_length=20)),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('religion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Employee',
            },
            bases=('employee.person',),
        ),
    ]
