# Generated by Django 3.1.1 on 2020-09-23 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='regdate',
            field=models.DateField(default=datetime.datetime(2020, 9, 23, 17, 52, 47, 2405)),
        ),
    ]
