# Generated by Django 3.1.1 on 2020-10-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
