# Generated by Django 3.1.1 on 2020-09-18 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='regdate',
            field=models.DateField(default=datetime.datetime(2020, 9, 18, 16, 3, 32, 912788)),
        ),
    ]
