# Generated by Django 3.1.1 on 2020-09-16 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='regdate',
            field=models.DateField(default=datetime.datetime(2020, 9, 16, 16, 26, 59, 118535)),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplierId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplierId',
            field=models.IntegerField(),
        ),
    ]
