# Generated by Django 3.1.1 on 2020-09-16 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200916_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='regdate',
            field=models.DateField(default=datetime.datetime(2020, 9, 16, 16, 37, 0, 871118)),
        ),
    ]
