# Generated by Django 3.1.1 on 2020-09-16 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200916_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='regdate',
            field=models.DateField(default=datetime.datetime(2020, 9, 16, 20, 6, 9, 604683)),
        ),
    ]
