# Generated by Django 3.1.1 on 2020-09-20 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200920_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='regdate',
            field=models.DateField(default=datetime.datetime(2020, 9, 20, 12, 37, 34, 871156)),
        ),
    ]
