# Generated by Django 3.1.1 on 2020-09-16 12:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200916_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplierId',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='supplierId',
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Supplier', to='inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='product',
            name='regdate',
            field=models.DateField(default=datetime.datetime(2020, 9, 16, 20, 53, 9, 681587)),
        ),
    ]
