# Generated by Django 3.1.1 on 2020-09-22 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200920_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='regdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
