# Generated by Django 3.1.1 on 2020-09-23 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200920_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='regdate',
            field=models.DateField(default=datetime.datetime(2020, 9, 23, 17, 49, 41, 687746)),
        ),
    ]
