# Generated by Django 3.1.1 on 2020-09-23 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20200922_1951'),
        ('inventory', '0008_auto_20200923_1752'),
    ]

    operations = [
    ]
