# Generated by Django 3.1.1 on 2020-10-09 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_order_orderedproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproducts',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.order'),
        ),
    ]
