# Generated by Django 3.1.1 on 2020-10-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20201010_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customerFName',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customerLName',
        ),
    ]
