# Generated by Django 3.1.1 on 2020-10-10 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20201010_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dateOrdered',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
